name: Deploy Seedream 3.0 Web UI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Update system & install dependencies
      - name: Install system packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y python3-pip python3-venv git wget ffmpeg

      # Step 3: Setup Python environment
      - name: Setup Python
        run: |
          python3 -m venv seedream_env
          source seedream_env/bin/activate
          pip install --upgrade pip

      # Step 4: Install PyTorch (CPU version)
      - name: Install PyTorch CPU
        run: |
          source seedream_env/bin/activate
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      # Step 5: Install Seedream dependencies
      - name: Install Python dependencies
        run: |
          source seedream_env/bin/activate
          pip install -r requirements.txt
          pip install fastapi uvicorn jinja2 python-multipart pillow

      # Step 6: Ensure models folder exists (user must place weights manually)
      - name: Prepare models folder
        run: |
          mkdir -p models
          echo "Please place Seedream 3.0 weights in the models/ folder."

      # Step 7: Ensure static folder exists
      - name: Create static folder
        run: mkdir -p static

      # Step 8: Run the FastAPI server (for testing; usually in VPS you use systemd)
      - name: Start Web UI server (test run)
        run: |
          source seedream_env/bin/activate
          nohup uvicorn app:app --host 0.0.0.0 --port 8000 &
          echo "Server started on port 8000"
