name: XFCE Desktop Access via ngrok and VNC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies x11vnc xvfb tmux dbus-x11 wget
          
          # Install ngrok
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          sudo unzip ngrok-stable-linux-amd64.zip -d /usr/local/bin/

      - name: Start VNC and ngrok tunnel
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          # Start XFCE inside a virtual display on display :99
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          
          # Set the VNC password non-interactively
          mkdir -p ~/.vnc
          x11vnc -storepasswd "$VNC_PASSWORD" ~/.vnc/passwd
          
          # Start the VNC server in the background
          tmux new-session -d -s vnc_session 'x11vnc -display :99 -forever -rfbauth ~/.vnc/passwd -rfbport 5900'
          
          # Authenticate ngrok and start the tunnel
          ngrok authtoken "$NGROK_AUTHTOKEN"
          nohup ngrok tcp 5900 > ngrok.log &
          
          # Wait for ngrok tunnel to become active and get the public URL
          sleep 10
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "VNC Tunnel is active! Connect via VNC client to:"
          echo ":: $NGROK_URL ::"
          
          # Keep the job alive for remote access
          sleep 3600
