name: Start Chrome Remote Desktop

on:
  workflow_dispatch:

jobs:
  start-crd:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-terminal dbus-x11 wget curl unzip

    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt -f install -y

    - name: Set CRD password
      run: |
        mkdir -p ~/.chrome-remote-desktop
        echo "123456" | sudo tee /etc/chrome-remote-desktop-password

    - name: Start Chrome Remote Desktop
      run: |
        export DISPLAY=:0
        /opt/google/chrome-remote-desktop/start-host --code="4/0AVMBsJilHDTj2xH8z-4zfCEhtEuTemq0d_Gq3FA1i-bhQKJjdhaR8UM2n_I2ogjJgMw8kg" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
