name: XFCE Desktop Access via VNC

on:
  # Allows you to manually trigger the workflow from the GitHub Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies x11vnc xvfb tmux

      - name: Start VNC server
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          # Start XFCE inside a virtual display
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
          # Start xfce4 in the virtual display
          xfce4-session &
          # Set the VNC password from the GitHub Secret
          echo "$VNC_PASSWORD" | x11vnc -storepasswd ~/.vnc_password
          # Start the VNC server in the background using tmux
          tmux new-session -d -s vnc_session 'x11vnc -display :99 -nopw -rfbauth ~/.vnc_password'
          # Wait for VNC to start and display connection details
          sleep 5
          echo "VNC Server is running on port 5900."

      - name: Display VNC details (for debugging)
        run: |
          echo "Connect to the VNC server to view the XFCE desktop."
          echo "Note: The runner IP is temporary and only accessible during the workflow run."

      # This step holds the job open for a specified duration, allowing time for VNC connection.
      - name: Keep job alive for remote access
        run: sleep 3600 # Wait for 1 hour for remote access
        
