name: XFCE Desktop Access via Pinggy and VNC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies x11vnc xvfb tmux
          # Pinggy requires no installation, just the `ssh` client
      
      - name: Start VNC and Pinggy tunnel
        env:
          VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
        run: |
          # Start XFCE inside a virtual display on display :99
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          
          # Set the VNC password non-interactively
          mkdir -p ~/.vnc
          x11vnc -storepasswd "$VNC_PASSWORD" ~/.vnc/passwd
          
          # Start xfce4 in the virtual display
          xfce4-session &
          
          # Start the VNC server in the background
          tmux new-session -d -s vnc_session 'x11vnc -display :99 -forever -rfbauth ~/.vnc/passwd -rfbport 5900 -xkb'

          # Start the Pinggy TCP tunnel and capture the output
          PINGGY_OUTPUT=$(ssh -p 443 -R 0:localhost:5900 a.pinggy.io -N &> pinggy.log & sleep 5 && cat pinggy.log)
          
          # Extract the tunnel URL from the output (Pinggy prints it to stderr)
          PINGGY_URL=$(echo "$PINGGY_OUTPUT" | grep -o 'tcp://[^[:space:]]*')
          
          if [ -z "$PINGGY_URL" ]; then
            echo "Failed to get Pinggy URL after retries."
            exit 1
          fi

          echo "VNC Tunnel is active! Connect via VNC client to:"
          echo ":: $PINGGY_URL ::"
          
          # Keep the job alive for remote access
          sleep 3600
